#               TSP

## Brute-Force Resolution

In [15]:

def perm(L):
    if len(L) == 1 or len(L) == 0:
        return [L]
    out =[] 
    for i in range(len(L)) :
        R = L[:i] + L[i+1:]
        for j in perm(R):
            out.append(j+[L[i]])
    return out

        
L = [0, 1, 2, 3]
perm(L)



[[3, 2, 1, 0],
 [2, 3, 1, 0],
 [3, 1, 2, 0],
 [1, 3, 2, 0],
 [2, 1, 3, 0],
 [1, 2, 3, 0],
 [3, 2, 0, 1],
 [2, 3, 0, 1],
 [3, 0, 2, 1],
 [0, 3, 2, 1],
 [2, 0, 3, 1],
 [0, 2, 3, 1],
 [3, 1, 0, 2],
 [1, 3, 0, 2],
 [3, 0, 1, 2],
 [0, 3, 1, 2],
 [1, 0, 3, 2],
 [0, 1, 3, 2],
 [2, 1, 0, 3],
 [1, 2, 0, 3],
 [2, 0, 1, 3],
 [0, 2, 1, 3],
 [1, 0, 2, 3],
 [0, 1, 2, 3]]

In [22]:
def loops(n, start):
    L = perm([i for i in range(n)])
    return [i + [i[0]] for i in L if i[0] == start]
    

loops(10,3)

[[3, 9, 8, 7, 6, 5, 4, 2, 1, 0, 3],
 [3, 8, 9, 7, 6, 5, 4, 2, 1, 0, 3],
 [3, 9, 7, 8, 6, 5, 4, 2, 1, 0, 3],
 [3, 7, 9, 8, 6, 5, 4, 2, 1, 0, 3],
 [3, 8, 7, 9, 6, 5, 4, 2, 1, 0, 3],
 [3, 7, 8, 9, 6, 5, 4, 2, 1, 0, 3],
 [3, 9, 8, 6, 7, 5, 4, 2, 1, 0, 3],
 [3, 8, 9, 6, 7, 5, 4, 2, 1, 0, 3],
 [3, 9, 6, 8, 7, 5, 4, 2, 1, 0, 3],
 [3, 6, 9, 8, 7, 5, 4, 2, 1, 0, 3],
 [3, 8, 6, 9, 7, 5, 4, 2, 1, 0, 3],
 [3, 6, 8, 9, 7, 5, 4, 2, 1, 0, 3],
 [3, 9, 7, 6, 8, 5, 4, 2, 1, 0, 3],
 [3, 7, 9, 6, 8, 5, 4, 2, 1, 0, 3],
 [3, 9, 6, 7, 8, 5, 4, 2, 1, 0, 3],
 [3, 6, 9, 7, 8, 5, 4, 2, 1, 0, 3],
 [3, 7, 6, 9, 8, 5, 4, 2, 1, 0, 3],
 [3, 6, 7, 9, 8, 5, 4, 2, 1, 0, 3],
 [3, 8, 7, 6, 9, 5, 4, 2, 1, 0, 3],
 [3, 7, 8, 6, 9, 5, 4, 2, 1, 0, 3],
 [3, 8, 6, 7, 9, 5, 4, 2, 1, 0, 3],
 [3, 6, 8, 7, 9, 5, 4, 2, 1, 0, 3],
 [3, 7, 6, 8, 9, 5, 4, 2, 1, 0, 3],
 [3, 6, 7, 8, 9, 5, 4, 2, 1, 0, 3],
 [3, 9, 8, 7, 5, 6, 4, 2, 1, 0, 3],
 [3, 8, 9, 7, 5, 6, 4, 2, 1, 0, 3],
 [3, 9, 7, 8, 5, 6, 4, 2, 1, 0, 3],
 [3, 7, 9, 8, 5, 6, 4, 2, 1,

In [32]:
def distance(LB, T):
    out = []
    for i in LB :
        dist = 0
        for j in range(len(i)-1):
            dist += T[i[j]][i[j+1]]
        out.append(dist)

    return out 


LB = loops(4, 2)

T = [
    [0, 5, 4, 9],
    [3, 0, 4, 7],
    [5, 1, 0, 2],
    [6, 2, 8, 0]
]

print(distance(LB, T))


[11, 18, 17, 20, 21, 25]


In [34]:
def best(LB,T):
    y = distance(LB,T)
    x = min(y)
    return (x, LB[y.index(x)])
best(LB,T)

(11, [2, 3, 1, 0, 2])

In [ ]:
import numpy as np
def cor_to_mat(LC):
    LC = np.array(LC)
    diff = LC[np.newaxis, :, :] - LC[:, np.newaxis, :]
    
    return np.linalg.norm(diff, axis=2)

LC = [(0, 0), (1, 1), (2, 4), (1, -3), (0, -5), (0, 4), (-1, -5), (-2, 3), (-3, 0)]

cor_to_mat(LC)

array([[0.        , 1.41421356, 4.47213595, 3.16227766, 5.        ,
        4.        , 5.09901951, 3.60555128, 3.        ],
       [1.41421356, 0.        , 3.16227766, 4.        , 6.08276253,
        3.16227766, 6.32455532, 3.60555128, 4.12310563],
       [4.47213595, 3.16227766, 0.        , 7.07106781, 9.21954446,
        2.        , 9.48683298, 4.12310563, 6.40312424],
       [3.16227766, 4.        , 7.07106781, 0.        , 2.23606798,
        7.07106781, 2.82842712, 6.70820393, 5.        ],
       [5.        , 6.08276253, 9.21954446, 2.23606798, 0.        ,
        9.        , 1.        , 8.24621125, 5.83095189],
       [4.        , 3.16227766, 2.        , 7.07106781, 9.        ,
        0.        , 9.05538514, 2.23606798, 5.        ],
       [5.09901951, 6.32455532, 9.48683298, 2.82842712, 1.        ,
        9.05538514, 0.        , 8.06225775, 5.38516481],
       [3.60555128, 3.60555128, 4.12310563, 6.70820393, 8.24621125,
        2.23606798, 8.06225775, 0.        , 3.16227766],


In [ ]:
def TSP(start, LC):
    T = cor_to_mat(LC)
    loop = loops(len(T), start)
    return best(loop, T)

LC = [(0, 0), (1, 1), (2, 4), (1, -3), (0, -5), (0, 4), (-1, -5), (-2, 3), (-3, 0)]




(23.758347305012315, [0, 1, 2, 5, 7, 8, 6, 4, 3, 0])

In [41]:
TSP(0, LC)


(23.758347305012315, [0, 1, 2, 5, 7, 8, 6, 4, 3, 0])

## The Genetic Algorithm

In [42]:
import random


In [56]:
def gen(N):
    return np.array([[random.randint(0,20), random.randint(0,20)]  for _ in range(N)])

In [89]:
def dublicated(arr): # to check for duplicated 
       return np.any(np.diff(np.sort(arr)) == 0)

L = gen(25)

while dublicated(L):
       print('-',end='')
       L = gen(25)

-----

In [90]:
M = cor_to_mat(L)

In [91]:
M

array([[ 0.        ,  1.        ,  5.09901951, 12.04159458,  7.07106781,
         7.21110255, 11.18033989,  9.43398113, 12.        , 14.4222051 ,
         8.94427191, 16.2788206 , 18.24828759,  8.06225775,  9.43398113,
         8.60232527,  9.8488578 , 12.04159458,  3.60555128,  3.16227766,
         8.94427191, 15.23154621,  3.60555128, 19.6977156 , 11.40175425],
       [ 1.        ,  0.        ,  5.        , 11.3137085 ,  7.28010989,
         6.70820393, 11.04536102,  8.94427191, 12.04159458, 13.60147051,
         8.06225775, 15.62049935, 17.2626765 ,  7.21110255,  8.94427191,
         8.06225775,  8.94427191, 11.3137085 ,  3.16227766,  3.60555128,
         8.54400375, 14.31782106,  3.16227766, 18.78829423, 10.44030651],
       [ 5.09901951,  5.        ,  0.        ,  8.54400375,  2.82842712,
        11.40175425,  6.08276253, 13.60147051,  7.07106781, 17.02938637,
        11.40175425, 12.20655562, 17.11724277,  6.08276253,  5.        ,
        12.64911064,  8.06225775,  8.54400375,  2

In [92]:
random.shuffle(L)

In [93]:
L

array([[ 8, 18],
       [ 8, 17],
       [ 8, 18],
       [ 8, 17],
       [13, 17],
       [16,  9],
       [ 2, 14],
       [ 0, 13],
       [15, 19],
       [20, 18],
       [ 2, 14],
       [15, 19],
       [ 0,  6],
       [ 8, 18],
       [ 8, 17],
       [16,  9],
       [12, 11],
       [ 1, 13],
       [ 4, 10],
       [13, 17],
       [16,  9],
       [ 0, 14],
       [12, 11],
       [13, 17],
       [20,  7]])

In [104]:
def Create_Init(N, L):
    index = [i for i in range(len(L))] 
    out = []
    for _ in range(N):
        random.shuffle(index)
        out.append(index)

    return np.array(out)

Create_Init(10,L)


array([[17,  3, 12,  6, 10,  9, 21,  0,  5, 15,  8, 16, 19, 13, 11,  7,
        20,  2,  1, 18,  4, 14, 23, 24, 22],
       [17,  3, 12,  6, 10,  9, 21,  0,  5, 15,  8, 16, 19, 13, 11,  7,
        20,  2,  1, 18,  4, 14, 23, 24, 22],
       [17,  3, 12,  6, 10,  9, 21,  0,  5, 15,  8, 16, 19, 13, 11,  7,
        20,  2,  1, 18,  4, 14, 23, 24, 22],
       [17,  3, 12,  6, 10,  9, 21,  0,  5, 15,  8, 16, 19, 13, 11,  7,
        20,  2,  1, 18,  4, 14, 23, 24, 22],
       [17,  3, 12,  6, 10,  9, 21,  0,  5, 15,  8, 16, 19, 13, 11,  7,
        20,  2,  1, 18,  4, 14, 23, 24, 22],
       [17,  3, 12,  6, 10,  9, 21,  0,  5, 15,  8, 16, 19, 13, 11,  7,
        20,  2,  1, 18,  4, 14, 23, 24, 22],
       [17,  3, 12,  6, 10,  9, 21,  0,  5, 15,  8, 16, 19, 13, 11,  7,
        20,  2,  1, 18,  4, 14, 23, 24, 22],
       [17,  3, 12,  6, 10,  9, 21,  0,  5, 15,  8, 16, 19, 13, 11,  7,
        20,  2,  1, 18,  4, 14, 23, 24, 22],
       [17,  3, 12,  6, 10,  9, 21,  0,  5, 15,  8, 16, 19, 13, 

In [ ]:
def best_indiv(population,M):
    
    
    
    return